stages:
  prepare:
    cmd: python project_aisc/src/features/preprocessing.py
    deps:
    - project_aisc/data/raw/supercon.csv
    - project_aisc/data/raw/garbage_in_50_000.csv
    - project_aisc/src/features/preprocessing.py
    params:
      - project_aisc/config/preprocessing.yaml:
    outs:
    - project_aisc/data/processed/test/X_test.npy
    - project_aisc/data/processed/test/Y_test.npy
    - project_aisc/data/processed/train/X_train.npy
    - project_aisc/data/processed/train/Y_train.npy
    - project_aisc/data/processed/val/X_val.npy
    - project_aisc/data/processed/val/Y_val.npy
  train:
    cmd: python project_aisc/src/laboratory/train_model.py
    deps:
    - project_aisc/data/processed/train/X_train.npy
    - project_aisc/src/laboratory/train_model.py
  evaluate:
    cmd: python project_aisc/src/laboratory/evaluate.py
